triton-inference-server/common

- include/triton/common/table_printer.h
- include/triton/common/triton_json.h
- src/table_printer.cc
```
I1028 17:00:44.879244 4497 server.cc:184] 
+-----------+---------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Model     | Version | Status                                                                                                                                                                                 |
+-----------+---------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| model_env | 1       | UNAVAILABLE: Internal: Traceback (most recent call last):
File …
```
> Fix multi-line fields for TablePrinter

- CMakeLists.txt
https://gitlab-master.nvidia.com/dl/dgx/tritonserver/-/pipelines/2290569
> Fix symbol definitiions in libasyncworkqueue.a

- include/triton/common/triton_json.h
Fixing https://github.com/triton-inference-server/server/issues/2893
and potential segfault issue in Append
> Fix segfault in Add

- include/triton/common/triton_json.h
Needed for TRT autofiller logic
> Adding API to set/overwrite string

- protobuf/model_config.proto
@deadeyegoodwin look and feel for the new field in model config
> Add optional field in ModelInput message

- protobuf/model_config.proto
The setting is based on ModelWarmup. I have removed the parameters that where not related such as batch size and random_data.
> Add state initialization setting to model config protobuf

- include/triton/common/triton_json.h
Adds two new functions to the TritonJson api for use in the tensorflow backend.
> Add Functions to TritonJson API

- include/triton/common/triton_json.h
Updated API definition as per [this PR comment](https://github.com/triton-inference-server/tensorflow_backend/pull/58/files/89b33db7e3d17460d733de89bf82d1aefacfa2b4#r871899294)
> SetString to SetStringObject in TritonJson API

- include/triton/common/logging.h
- src/logging.cc
Default
```
I0523 23:49:06.674147 141 server.cc:288] All models are stopped, unloading models
```
ISO8601
```
2022-05-23T23:49:14 I 153 server.cc:288] All models are stopped, unloading models
```
> Add different logging format

- CMakeLists.txt
- include/triton/common/async_work_queue.h
- include/triton/common/thread_pool.h
- src/async_work_queue.cc
- src/thread_pool.cc
Backend: https://github.com/triton-inference-server/backend/pull/62
Common: https://github.com/triton-inference-server/common/pull/63
Core: https://github.com/triton-inference-server/core/pull/89
> Use thread_pool in async_work_queue internally

- include/triton/common/triton_json.h
Using `rapidjson::Value(static_cast<rapidjson::Type>(type))` to create Value causes memory leak even using allocator to release the object. Changed to use `allocator_->Malloc()` to create Value and modified `Releae()` function accordingly.
Related PRs:
backend: https://github.com/triton-inference-server/backend/pull/67
tensorrt_backend: https://github.com/triton-inference-server/tensorrt_backend/pull/44
server: https://github.com/triton-inference-server/server/pull/4693
> Fix rapidjson memory leak issue

- include/triton/common/logging.h
- protobuf/grpc_service.proto
- src/logging.cc
Rebase error occurred with original branch. Attempting to migrate changes to new branch.
> Incorporating Dynamic Logging

- protobuf/model_config.proto
Merging uint64 change in for testing and further changes to protobuf files
> change priority from uint32 to uint64 in model_config

- include/triton/common/error.h
core: https://github.com/triton-inference-server/core/pull/249
> Add cancellation error code

- include/triton/common/error.h
Bringing in changes from the request cancellation branch.
> Add cancellation error code (#99)

- protobuf/model_config.proto
* Add same input/output bstate buffer option
* Add an option for using GrowableMemory
* Review comments
* Format
* Review comments
* Review comment
* Fix description
> Add options for growable memory and single state buffers (#104)

- protobuf/grpc_service.proto
Server: https://github.com/triton-inference-server/server/pull/6755
Core: https://github.com/triton-inference-server/core/pull/307
PYBE: https://github.com/triton-inference-server/python_backend/pull/333
Identity Backend: https://github.com/triton-inference-server/identity_backend/pull/28
Client: https://github.com/triton-inference-server/client/pull/453
> Support Double-Type Inference Request/Response Parameters

- protobuf/grpc_service.proto
Related PRs:
- https://github.com/triton-inference-server/server/pull/6869
- https://github.com/triton-inference-server/core/pull/325
- https://github.com/triton-inference-server/square_backend/pull/16
Add response statistics protobuf change.
> Add response statistics

- include/triton/common/thread_pool.h
- src/thread_pool.cc
Add a new API "EnqueueIfCapacityAvailable" to ThreadPool for efficient task enqueue.
Check the [conventional commit type](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type)
box here and add the label to the github PR.
https://github.com/triton-inference-server/core/pull/429
L0_infer--base
L0_simple_ensemble--base
L0_build_variants--build
- CI Pipeline ID:
26417161
- closes GitHub issue: #7650
> feat: Ensemble async callback execution

- include/triton/common/thread_pool.h
- src/thread_pool.cc
Reverts triton-inference-server/common#133
> Revert "feat: Ensemble async callback execution"

- include/triton/common/thread_pool.h
- src/thread_pool.cc
This reverts commit a32ce03c92abdfb5a2a360127ed4b7199ecb38fd.
> Revert "feat: Introduce TaskQueueSize() for ThreadPool (#133)" (#135)
