include/triton/common/triton_json.h

Suppress `class-memaccess` warnings in RapidJSON header to work around https://github.com/Tencent/rapidjson/issues/1700.
This change allows compilation with gcc>=8 to proceed normally.

Suppress RapidJSON warning to allow gcc>=8 compilation

---

protobuf/model_config.proto

Example of how to specify secondary devices in model config
```
instance_group [
{
kind: KIND_GPU
secondary_devices [
{
kind: KIND_NVDLA 
device_id: 1
}
]
}
]
```

Add support for DLA/secondary device specification

---

protobuf/model_config.proto

Note that the numa id for GPU instance will always be the same as the gpu id, this is because in proto3 there is no way to tell if a primitive type is set explicitly or the default value is used, i.e. 0 can either be the user sets the id to 0 or the user doesn't set the value. Which will be confusing for GPU instance because the default behavior for GPU instance is that instances on different GPU device will be assigned to different numa id, but we can't differentiate the meaning of 0 here.
If we really want to be able to overwrite numa id for GPU instances, a work around is to wrap the numa id in a protobuf message so we will check if the message is specified to determine if the numa id is set explicitly.

Add host policy field

---

tools/pre-commit

Integrating the formatter into git workflow is a nice thing to have. To use that, just copying `pre-commit` and `format.py` into `.git/hooks/` of the desired repo

Add git pre-commit script to use with format.py

---

include/triton/common/nvtx.h

Needed in common because both server and backend can use this.

Add NVTX macros to common repo

---

src/table_printer.cc

* allows the compiler to do copy elision
* allows compiling on newer clang versions with -Werror

Fix pessimizing move in function return

---

CMakeLists.txt
README.md
cmake/TritonCommonConfig.cmake.in
protobuf/CMakeLists.txt

Hello, *!
I've done the following things for the cmake build of this project:
* remove extra whitespace
* use the @PACKAGE_INIT@ variable to add functionality to the
config.cmake - see: https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html
* remove unused find_dependency cmake include - wasn't used, but in fact it should be - and it should search for RapidJSON which is a public dependency - the problem is the version usually installed on ubuntu has an old cmake config file which does not expose targets. this makes it hard for the triton-common project to work correctly when installed
* update minimum cmake version in readme (was 3.14 when the project needs at least 3.17 - from the cml)
There are some other things that can be done to improve the build system: adding a …

Refactor cmake scripts

---

include/triton/common/async_work_queue.h
src/async_work_queue.cc

Hi!
* even though there was a std::move in `AddTask`, it would do nothing
looking at the callstack we can see it actually calls `Put(const&)` all
the time, see this similar example: https://godbolt.org/z/d9xqKT6jx
Does it really help for it to be const? Is there a reason a copy is `wanted` for those `std::functions`? The semantics I know for `const&&` revolve around `users can't use lvalues, but we'll still copy the value they pass`.
Maybe I missed something tho so please let me know!
Thanks

Fix const&& won't allow std::move in AddTask

---

CMakeLists.txt
protobuf/CMakeLists.txt

This PR adds a few CMake options to help address https://github.com/triton-inference-server/server/issues/3141:
* `TRITON_COMMON_ENABLE_PROTOBUF_PYTHON`, on by default. If turned off, will avoid building python artifacts when just c++ artifacts are needed.
* `TRITON_COMMON_ENABLE_JSON`, on by default. If turned off, will avoid building json-related libraries, which are not always needed and involve additional dependencies.
This PR goes with https://github.com/triton-inference-server/client/pull/95.

CMake fixes

---

CMakeLists.txt
include/triton/common/model_config.h
src/model_config.cc

Addresses https://github.com/triton-inference-server/server/issues/2759: many of the functions in `model_config.h` are generically useful even on the client side and only depend on the generated protobuf headers. Therefore, it is useful to have them more broadly accessible via the common repo.
The header and cc files are copied here from the core repo (except for a few functions with non-trivial dependencies that stay in core), with the namespace changed to `triton::common`. A new library `triton-common-model-config` is built. Because many of the functions depend on the generated protobuf headers, this library is only built when the protobuf part of this repo is enabled.
This PR goes with https://github.com/triton-inference-server/core/pull/60.

Move model_config to common

---

CMakeLists.txt
cmake/TritonCommonConfig.cmake.in
include/triton/common/thread_pool.h
src/thread_pool.cc

Add simple ThreadPool implementation that doesn't rely on `boost::asio`
[common] Adds custom ThreadPool implementation in common: https://github.com/triton-inference-server/common/pull/60
[core] Use thread pool for loading models in model_repository_manager.cc: https://github.com/triton-inference-server/core/pull/86
[server] Expose num threads to server CLI: https://github.com/triton-inference-server/server/pull/4500
> NOTE: Will update `AsyncWorkQueue` to use `ThreadPool` internally in a follow-up ticket (DLIS-3860) to only maintain one implementation, and not have `ThreadPool` be restricted to only being a singleton like AsyncWorkQueue currently is.

Add ThreadPool to common

---

include/triton/common/triton_json.h

Non-Docker Windows compilation fails on some machines due to a preprocessor macro for GetObject redefining GetObject to GetObjectA/GetObjectW in `windows.h`. The fix was imported to the main branch of RapidJSON last year (using GetObj as an alias for GetObject). However, there has not been a release of RapidJSON since 2016 and there is not one planned yet.
Undefining the preprocessor macro resolves this compilation failure for Windows machines.
See RapidJSON issue thread here: https://github.com/Tencent/rapidjson/issues/1448

Remove Name Collision (GetObject)

---

CMakeLists.txt
protobuf/CMakeLists.txt
protobuf/grpc_service.proto
protobuf/health.proto
protobuf/model_config.proto

Add GRPC's standard health check protocol. This can be used with tools like grpc-health-probe and Kubernetes liveness probes (as of [Kubernetes 1.24](https://kubernetes.io/blog/2022/05/13/grpc-probes-now-in-beta/)).
Related server PR (implementation, tests): https://github.com/triton-inference-server/server/pull/5267

Add protobuf for GRPC health check

---

include/triton/common/triton_json.h
protobuf/grpc_service.proto
protobuf/model_config.proto

Updating priority levels within model config proto to support uint64 (allows for utilizing timestamps as priority).
See discussion here https://github.com/triton-inference-server/common/pull/82#issuecomment-1547650136.
In addition update the InferParameter choices to include double and uint64.
Double is to keep consistent with other inference servers - in anticipation of KServe protobuf's changes.

Updating Service and Model Config Protobuf for uint64 Request Priority

---

tools/format.py

The build container is now built on Ubuntu 22.04, which has clang-format-11 through clang-format-15. As a result, I'd like to update the clang format version so that we can continue to use it in the build container.
This is tested locally. When run on already-formatted files, it formats minimally. It does look like 15 has a few changes from clang-format-6.0 but the format generally makes sense.

Update clang format version

---

protobuf/model_config.proto

Common: https://github.com/triton-inference-server/common/pull/97
Core: https://github.com/triton-inference-server/core/pull/241
Server: https://github.com/triton-inference-server/server/pull/6185

Add preserve_ordering field to oldest strategy in sequence scheduler config

---

protobuf/model_config.proto

* name change
* updated language
* updated with default value
* updated language

Generative ->Iterative (#107)

---

protobuf/model_config.proto

Related PRs:
* https://github.com/triton-inference-server/server/pull/6518
* https://github.com/triton-inference-server/core/pull/285
* https://github.com/triton-inference-server/backend/pull/94
* https://github.com/triton-inference-server/pytorch_backend/pull/117
The user can now choose the "runtime" for each model, for example:
```
runtime: "libtriton_tensorrt.so"
```
```
runtime: "model.py"
```

Add runtime to model configuration

---

CMakeLists.txt

This PR is one of the series PRs to update Triton to C++17 standard.
Introduced logic: either set `TRITON_MIN_CXX_STANDARD` to 17 or use cached value. Later,`TRITON_MIN_CXX_STANDARD`  is used to set min required standard through `target_compile_features`.

Bump min cxx standard to 17

---

protobuf/grpc_service.proto

Related PRs:
- https://github.com/triton-inference-server/server/pull/6904
- https://github.com/triton-inference-server/core/pull/329
- https://github.com/triton-inference-server/square_backend/pull/17
Add cancellation statistics field into response statistics.

Add cancellation into response statistics

---

include/triton/common/error.h
include/triton/common/logging.h
include/triton/common/triton_json.h
src/CMakeLists.txt
src/logging.cc

- Added support for escaping log messages by default
- Added environment variable to disable escaping
- refactored windows support to simplify deltas
- added macros for logging Protobuf, and Table objects w/o escaping 
- https://github.com/triton-inference-server/server/pull/7219
- https://github.com/triton-inference-server/core/pull/355
<details>
<summary>Original Log Examples</summary>
[log_file_orig.log](https://github.com/triton-inference-server/common/files/15327573/log_file_orig.log)
</details>
<details>
<summary>Log File All Strings Escaped</summary>
[log_file_escaped.log](https://github.com/triton-inference-server/common/files/15327571/log_file_escaped.log)
</details>
<details>
<summary>Log File with Special Handling for Protobuf, table, and ServerMessage objects</summary> …

Update default log formats to escape messages using JSON encoding rules

---

include/triton/common/logging.h

During compilation in certain environments `std::array` is not being included.

adding explicit include of array needed for some environments

---

include/triton/common/error.h
include/triton/common/logging.h
include/triton/common/triton_json.h
src/CMakeLists.txt
src/logging.cc

log format cherry picks (#117 ) (#116 )

---

include/triton/common/logging.h

The common logging library is compiled and incorporated as a static library. When including the logging.h file in other projects the winsock apis can conflict and thus we need to guard against including them. 
This is a similar pattern to: 
https://github.com/triton-inference-server/server/blob/ab5bedc63752f4fdfab4c0d8bd8ddf4630e76573/src/main.cc#L29

fix: guard windows api definitions in logging.h

---

protobuf/CMakeLists.txt

**Goal:** Fix the Windows build which was failing to compile c++17 features due the GRPC repo bump in our third party repo.

build: Extend Common Compile Settings to Protobuf

---

protobuf/CMakeLists.txt

**Goal:** Fix the Windows build which was failing to compile c++17 features due the GRPC repo bump in our third party repo.

[Cherry Pick] build:Extend Common Compile Settings to Protobuf

---

include/triton/common/triton_json.h
protobuf/model_config.proto

- Added support for the `is_non_linear_format_io` flag in the model configuration to identify if input/output tensors use a non-linear IO format.

Fix shape and reformat free tensor handling in the input byte size check

---

include/triton/common/error.h

Add include for cstdint in error.h

Add support for building on Ubuntu 24.04

---

include/triton/common/error.h
protobuf/model_config.proto

Tests new model_metrics message in pbtxt. Add example to override histogram buckets per-family.
Check the [conventional commit type](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type)
box here and add the label to the github PR.
https://github.com/triton-inference-server/core/pull/405
https://github.com/triton-inference-server/server/pull/7752
L0_metrics
- CI Pipeline ID:
20106057
Default histogram buckets does not satisfy all use cases.

feat: Add model_metric message

---

CMakeLists.txt

This PR enables support for Ubuntu 24.04 by adding a new job to the CI workflow.

Enable support for Ubuntu 24.04

---

include/triton/common/thread_pool.h
src/thread_pool.cc

Add `TaskQueueSize` to ThreadPool class.
Previous PR: https://github.com/triton-inference-server/common/pull/133

feat: Ensemble async callback execution (rework)

---

include/triton/common/logging.h
src/logging.cc

Previously, all triton logs (INFO, WARNING, ERROR) are written into `stderr`. Changing the output stream of INFO log to `stdout`.
Some common practive I found `stdout` vs `stderr`. As @rmccorm4 mentioned, it seems relatively standard practice to log info stdout and warn/error+ to stderr for enterprise applications.
- https://stackoverflow.com/questions/4919093/should-i-log-messages-to-stderr-or-stdout
- https://overcast.blog/managing-container-stdout-stderr-logs-like-a-pro-e7d42ab0035e
Test PR: https://github.com/triton-inference-server/server/pull/8236

fix: Set correct log output stream
